{
 "title": "Kubernetes / View / Overall Summary",
 "tags": [
  "kubernetes-integration",
  "efficiency"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "node",
    "label": "node",
    "query": {
     "query": "label_values(node_filesystem_avail_bytes, instance)"
    }
   },
   { "name": "namespace", "query": { "query": "label_values(namespace)" } },
   {
    "name": "application",
    "query": {
     "query": "label_values({namespace=\"$namespace\"}, deployment)"
    }
   },
   {
    "name": "job",
    "query": {
     "query": "label_values({namespace=\"$namespace\"}, cronjob)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Number of nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "count(kube_node_info)" }
   ]
  },
  {
   "title": "Number not ready",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(kube_node_status_condition{condition=\"Ready\",status=\"false\"}) == 1"
    }
   ]
  },
  {
   "title": "Total CPU",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity{resource=\"cpu\",unit=\"core\"})"
    }
   ]
  },
  {
   "title": "Total memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity{resource=\"memory\", unit=\"byte\"}) / 2^30"
    }
   ]
  },
  {
   "title": "Pods Created",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "count(kube_pod_start_time)" }
   ]
  },
  {
   "title": "Pods Evicted",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_status_reason{ reason=\"Evicted\"} == 1)"
    }
   ]
  },
  {
   "title": "Efficiency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Average CPU Utilization",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate) / sum(kube_node_status_capacity{resource=\"cpu\"})"
    }
   ]
  },
  {
   "title": "Max CPU Utilization",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate) / sum(kube_node_status_capacity{resource=\"cpu\"})"
    }
   ]
  },
  {
   "title": "Average Memory Utilization",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container!=\"\", image!=\"\"}) / sum(machine_memory_bytes)"
    }
   ]
  },
  {
   "title": "Max Memory Utilization",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container!=\"\", image!=\"\"}) / sum(machine_memory_bytes)"
    }
   ]
  },
  {
   "title": "Cluster CPU Utilization Efficiency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests)",
     "legendFormat": "requests"
    },
    {
     "expr": "sum(cluster:namespace:pod_cpu:active:kube_pod_container_resource_limits)",
     "legendFormat": "limits"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate)",
     "legendFormat": "Utilization (CPU seconds)"
    }
   ]
  },
  {
   "title": "Cluster Memory Utilization Efficiency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(cluster:namespace:pod_memory:active:kube_pod_container_resource_requests)",
     "legendFormat": "requests"
    },
    {
     "expr": "sum(cluster:namespace:pod_memory:active:kube_pod_container_resource_limits)",
     "legendFormat": "limits"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{container!=\"\", image!=\"\"})",
     "legendFormat": "Utilization"
    }
   ]
  },
  {
   "title": "CPU Usage by Pods",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "milicore", "label": "milicore (m)" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\",  pod=~\"$application.*\", pod!=\"POD\"}) by (pod) * 1000",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "avg(cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests{namespace=\"$namespace\", pod=~\"$application.*\"}) * 1000",
     "legendFormat": "Requests"
    },
    {
     "expr": "avg(cluster:namespace:pod_cpu:active:kube_pod_container_resource_limits{namespace=\"$namespace\", pod=~\"$application.*\"}) * 1000",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Memory Usage by Pod",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", container!=\"\", image!=\"\", pod=~\"$application.*\"}) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "avg(cluster:namespace:pod_memory:active:kube_pod_container_resource_requests{namespace=\"$namespace\", pod=~\"$application.*\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "avg(cluster:namespace:pod_memory:active:kube_pod_container_resource_limits{namespace=\"$namespace\", pod=~\"$application.*\"})",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "CPU Usage by Job",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "milicore" } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\",  pod=~\"$job.*\", pod!=\"POD\"}) by (pod) * 1000",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "avg(cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests{namespace=\"$namespace\", pod=~\"$job.*\"}) * 1000",
     "legendFormat": "Requests"
    },
    {
     "expr": "avg(cluster:namespace:pod_cpu:active:kube_pod_container_resource_limits{namespace=\"$namespace\", pod=~\"$job.*\"}) * 1000",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Memory Usage by Job",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", container!=\"\", image!=\"\", pod=~\"$job.*\"}) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "avg(cluster:namespace:pod_memory:active:kube_pod_container_resource_requests{namespace=\"$namespace\", pod=~\"$job.*\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "avg(cluster:namespace:pod_memory:active:kube_pod_container_resource_limits{namespace=\"$namespace\", pod=~\"$job.*\"})",
     "legendFormat": "Limits"
    }
   ]
  }
 ]
}